#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-0 -d 2 3 4 5 6 7 8 9
bspc monitor HDMI-A-0 -d 1

bspc config borderless_monocle false
bspc config single_monocle true
bspc config gapless_monocle false
bspc config border_width         1
bspc config split_ratio          0.5
bspc config focused_border_color \#FFFFFF
bspc config normal_border_color \#000000
bspc config window_gap          8
bspc config focus_follows_pointer true

bspc rule -a "*:discord" desktop=^1 follow=off
bspc rule -a "*:brave" desktop=^2 follow=off
bspc rule -a Zathura state=tiled

xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rate 240 --pos 1080x500 --rotate normal --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --mode 1920x1080 --rate 144 --pos 0x0 --rotate right
nitrogen --restore
picom -b
killall -q polybar
polybar
~/.config/bspwm/swallow.sh
